version: "3.8"

services:
  geoapi-postgres-service:
    image: postgis/postgis
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  geoapi-app:
    build: .
    command: python3 app/main.py
    ports:
      - "8080:8080"
    depends_on:
        - geoapi-postgres-service